### ISSUE TITLE
How to handle long wand names

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/wand-nft#25]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/524089/178215325-e28a5b69-dbb0-4113-a729-90a94739b665.png">

**Comment by samepant** [comment]
That's pretty rough. We'll need to change the naming system to only allow for a maximum character limit.

**Comment by nginnever** [comment]
this is an interesting challenge, we were using random seeds to select the names which implies we would need check each word and its length and then find a way to get smaller words if over..

Maybe there is a simple approach.

- no random generation
- all combinations are less than max length
- drop a word if length over

i'll keep thinking about this too

**Comment by samepant** [comment]
One really simple (maybe too simple) approach could be to replace the word list with shorter words, so any combination of 4 will never be longer than the max amount. I think @keikreutler  was tinkering with replacing some of the wordlist at some point as well.

**Comment by samepant** [comment]
Talked to marv on discord a bit about this, and he brought up animating the name — i kinda love it, and it's all in SVG



https://user-images.githubusercontent.com/6718506/180514547-4e660d20-905d-4484-a4ce-044ac8e4d43d.mp4

**Comment by samepant** [comment]
fixed in #47
