### ISSUE TITLE
XP and Reputation

### ISSUE THREAD

**Issue by samepant** [gnosis/wand-nft#34]
Our NFT should track contributions to the Zodiac ecosystem over time. The [current proposed method](https://docs.google.com/document/d/1DTv0JaTTQw9p42G-TU2VkH5xbe4SYxS7jjz_GmoRRN4/edit) for doing this involves two metrics:
- Item Level (ILvl): This is the upgraded level of a specific Portal. As an avatar (wallet address) accrues XP, their equipped Portal will increase in level, which increases its visual complexity and ornateness. Item Level cannot be downgraded and persists even when a Portal is transferred to a new owner. This means a high level Portal will retain its visual appearance even when transfered.
- Experience Points (XP): This is the representation of a Portal holder’s contributions to the Zodiac ecosystem, which is awarded through peer-to-peer evaluations on a cyclical basis. A certain level of XP confers the ability to participate in Zodiac governance. XP is fundamentally associated with an avatar (wallet address), meaning that even if a Portal is traded away, the avatar will retain its XP and associated governance power. XP cannot be downgraded, unless a council questions whether an avatar itself has been transferred and therefore should have reduced governance power.

**Visualizing XP grants increasing Portal Item Level and Account XP**
<img src="https://user-images.githubusercontent.com/6718506/179581843-11e3147a-d2f8-4ce2-8498-b0ba84dd5525.png" width="400" style="margin: 0 auto">

**Visualizing transfer behavior of Portal NFT**
<img src="https://user-images.githubusercontent.com/6718506/179581864-5c6cd4da-8df1-4abc-bcc8-9a89f5b1257e.png" width="400" style="margin: 0 auto">

**Comment by samepant** [comment]
@nginnever made headway [on the XP and ILvl system here](https://github.com/gnosis/wand-nft/blob/rep/contracts/contracts/reputation/Forge.sol). 

I'm new to solidity so these questions are pretty uninformed — 
- Is there a way in `Forge.sol` to query an Account's current XP level? 
- Is XP mapped to an NFT token Id or an NFT holder's address? 

I also want to make sure it is flexible enough to handle these use cases:
- **XP does not transfer with an NFT**
    - This is key because we will use XP to confer rights to various Zodiac resources and governance, and we don't want this access to be bought/sold/trade-able with the NFT
    - _Scenario_: Lisa's account has a NFT, and Lisa receives `150` XP for her contributions, and can now edit [zodiac.wiki](zodiac.wiki). Lisa upgrades her NFT's ILvl to `2`, affecting its appearance. Lisa trades her NFT to Ryan, who has never contributed and has an XP of `0`. Ryan now has an ILvl 2 NFT, but no edit rights for zodiac.wiki; Lisa now has no NFT, but still has edit rights for zodiac.wiki.

- **XP should not be able to upgrade multiple NFT's ILvl**
    - It is possible for an account to hold multiple of our NFTs, so the ILvl upgrade process should restrict how XP is applied to prevent an account from upgrading multiple NFTs at once.
    - _Scenario_: Pippa has 3 NFTs all `ILvl = 0`, and receives enough XP to upgrade to the first ILvl. Pippa selects 1 of her NFTs to `Forge` into a `ILvl = 1`. Pippa can no longer upgrade any other of her NFTs, until she gets more XP.
    - This implies tracking two views of XP — 'unspent' and 'total', with one being a variable amount that can be spent to upgrade an NFT's ILvl, and the other being the total amount of XP received by an account, which can be used for gating Zodiac resources.

- **XP should be able to be decreased by the contract Owner**
   - It is possible a high XP account could be traded to someone who should not have access to Zodiac resources. We should have a way to remove XP from an account.
   - _Scenario_: Carl is an NFT holder with a lot of XP, and has contributed a lot to the Zodiac community. Carl gives his high XP account to Deedra, who has never participated in the Zodiac community. The Zodiac community notices this swap and enacts a governance process to remove the XP from Deedra's account.

**Comment by nginnever** [comment]
Thanks for having a look, this is all just how this currently works and if there are other ideas I can switch things up.

>Is there a way in Forge.sol to query an Account's current XP level?

The account XP state is stored by Forge.sol so it has access to this. The XP then determines how high of an item level an account is able to assign to a portal NFT. The NFT contract an then read the item level from the forge to select which SVG to render.

>Is XP mapped to an NFT token Id or an NFT holder's address?

Account address. I had accidentally mapped this to int but the was not correct, this is fixed now. So we have the following.

```
Address -> XP score
XP - > Increases iLvl
```

>XP does not transfer with an NFT

XP is forever bound to an account and has no transfer functionality (aside from selling the private key of an account which is likely infeasible for most situations)

>XP should not be able to upgrade multiple NFT's ILvl

Thanks for bringing this requirement up, i did not think about this. I will add some code to make iLvl upgrade "redeem" XP for an account, this will likely require tracking a struct will more state about how much XP an account has claimed.

>XP should be able to be decreased by the contract Owner

This is handled, the owner sets the XP and can set the XP lower if desired by a DAO.

**Comment by cristovaoth** [comment]
@nginnever was busy today with fixing stone interpolation. will dive into this tomorrow

**Comment by auryn-macmillan** [comment]
> Lisa now has no NFT, but still has edit rights for zodiac.wiki.

My understanding of this is that Lisa loses her edit rights until they equip another portal. One must have both an equipped portal and enough XP to gain edit rights.

Everything else aligns with my understanding of what we've previously discussed.

**Comment by samepant** [comment]
> My understanding of this is that Lisa loses her edit rights until they equip another portal. One must have both an equipped portal and enough XP to gain edit rights. 

Ah ok, that makes sense. Should we have a public function that returns a Boolean for whether or not an account has access to Zodiac resources? or should this be handled by a subgraph / application logic

> Do we wanna make level up thresholds static? Right now they are 1000, 5000 and 10000. Would it make sense to let owner redefine them?

I think making the thresholds settable by the Owner makes sense. Although I'm not sure what should happen to existing wand levels if the thresholds are raised.

> What is the role of maxLevel? 
> @samepant how many levels can our wand render? The current logic encoded by the Forge has no ceiling. It will upgrade the level, as long as unassigned XP are available. Maybe maxLevel was to be used here?

We currently have designs for 5 levels, although I can see this changing in the future. I think using the maxLevel to limit how high the level can go makes sense. Then if/when we add more levels we can increase maxLevel in the future.

**Comment by nginnever** [comment]
>Do we wanna make level up thresholds static? Right now they are 1000, 5000 and 10000. Would it make sense to let owner redefine them? I guess in case of governance changes we could later redeploy a new forge and swap it at wand level.

I was thinking we could make the thresholds permissioned variables, as long as we maintain an API that returns ints for the NFT contract to read as the selector for SVG components, I think this will work.

>@samepant how many levels can our wand render? The current logic encoded by the Forge has no ceiling. It will upgrade the level, as long as unassigned XP are available. Maybe maxLevel was to be used here?

Right as Sam mentioned, i think we might just need it if we are making adjustable limits in the XP. But it may be unnecessary, will experiment.

>Should we have a public function that returns a Boolean for whether or not an account has access to Zodiac resources? or should this be handled by a subgraph / application logic

if we just need to know a `balanceOf() >= 1` app logic / subgraph should work.
