### ISSUE TITLE
NFTs should be unique by Name

### ISSUE THREAD

**Issue by samepant** [gnosis/wand-nft#60]
When minting an NFT, we create a name using the [wordlist in WandName.sol](https://github.com/gnosis/wand-nft/blob/master/contracts/contracts/WandName.sol). Once a name is created, it should not be able to be used again by another mint, making each NFT unique by its name.

**Comment by cristovaoth** [comment]
@samepant our current scheme already achieves quite a bit of uniqueness. Up until tokenId 31213, it already generates unique names.

Given the cyclical (modulus division) nature of the seed, we can achieve quite a bit of unique names. This is based on actions, adjectives and nouns having different lengths. Currently we have:

- actions -> 83
- adjectives -> 103
- nouns -> 101

It might be even counter intuitive, but just by lowering lengths of (actions, adjectives, nouns) to (83, 84, 85), we raise the number of unique ids to around 500K. This would require throwing some names away.

Or we raise the lengths to (101, 102,103).

Thoughts?

**Comment by cristovaoth** [comment]
I also noticed, actions are Alphabetical, and adjectives and nouns are shuffled. On purpose?

**Comment by samepant** [comment]
given how we are generating names (with a seed) we will have unique names as long as we cap the token count at some point
